[tool.poetry]
name = "Rin"
version = "2.2.9"
description = "A Discord bot focused on obtaining data from third-party services with lighting performance in mind"
authors = ["No767 <73260931+No767@users.noreply.github.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
py-cord = {extras = ["voice"], version = "^2.3.2"}
python-dotenv = "^0.21.0"
uvloop = "^0.17.0"
aiodns = "^3.0.0"
Brotli = "^1.0.9"
orjson = "^3.8.3"
pysimdjson = "^5.0.2"
asyncpraw = "^7.6.1"
gql = {extras = ["aiohttp"], version = "^3.4.0"}
python-dateutil = "^2.8.2"
rin-exceptions = "^1.0.3"
numpy = "^1.24.1"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
asyncpg = "^0.27.0"
tortoise-orm = {extras = ["accel"], version = "^0.19.2"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
